<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Default test"
           tests="6"
           failures="1"
           errors="0"
           skipped="0"
           time="826.553">
  <properties />
            <testcase name="TC080DUL_10" time="455.605" classname="com.dts.adminportal.dts.test.DTSUser080DUserList">
                <failure type="java.lang.AssertionError"
                  message="(null)"
              >
<![CDATA[java.lang.AssertionError
  org.junit.Assert.fail(Assert.java:92)
  org.junit.Assert.assertTrue(Assert.java:43)
  org.junit.Assert.assertTrue(Assert.java:54)
  com.dts.adminportal.util.MailUtil.waitForNewInboxMessage(MailUtil.java:132)
  com.dts.adminportal.dts.test.DTSUser080DUserList.TC080DUL_10(DTSUser080DUserList.java:195)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:774)
  org.testng.TestRunner.run(TestRunner.java:624)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
  org.testng.SuiteRunner.run(SuiteRunner.java:261)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
  org.testng.TestNG.run(TestNG.java:1024)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="TC080DUL_07" time="65.087" classname="com.dts.adminportal.dts.test.DTSUser080DUserList" />
                <testcase name="TC080DUL_08" time="166.528" classname="com.dts.adminportal.dts.test.DTSUser080DUserList" />
                <testcase name="TC080DUL_04" time="36.504" classname="com.dts.adminportal.dts.test.DTSUser080DUserList" />
                <testcase name="TC080DUL_13" time="25.716" classname="com.dts.adminportal.dts.test.DTSUser080DUserList" />
                <testcase name="TC080DUL_09" time="77.113" classname="com.dts.adminportal.dts.test.DTSUser080DUserList" />
      
</testsuite>
